CREATE TABLE LOG_CONSULTA  (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  CONSULTA TEXT,
  ID_USUARIO INTEGER,
  NAME_USUARIO TEXT,
  USERNAME_USUARIO TEXT,
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME,
  R_USUARIO TEXT
);